### ISSUE TITLE
Error: $sce:insecurl Processing of a Resource from Untrusted Source Blocked

### ISSUE THREAD

**Issue by petermiles** [JohnnyTheTank/angular-wikipedia-api-factory#2]
I'm trying to load information from the wikipedia api but this is the error that I'm receiving:

https://docs.angularjs.org/error/$sce/insecurl?p0=https:%2F%2Fen.wikipedia.org%2Fw%2Fapi.php

Here is my code.

`
angular
  .module("plantsApp")
  .controller("plantCtrl", function($scope, plantServ, wikipediaFactory) {
    $scope.data = plantServ.data;
    $scope.submitInput = plantServ.sortData;
'
'
    wikipediaFactory
      .getArticle({
        term: "Abies"
      })
      .then(function(_data) {
        console.log(_data);
      });
  });
`

**Comment by JohnnyTheTank** [comment]
use angular 1.5.x, then it will work

**Comment by petermiles** [comment]
Thanks for the quick reply. Worked like a charm
